language: python

python:
    - "2.7"

install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - npm install -g jshint

script:
    - make -s

after_success:
    - coveralls
